spring:
  profiles:
    active: local  # ?? "dev", "prod" ? ?? ??
  application:
    name: buy-or-not

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---

# application-local.yml (H2 ????)
spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

